spring:
  datasource:
    url: jdbc:postgresql://dpg-ch1d1apmbg5847fkkj5g-a.oregon-postgres.render.com/dbuser_5ws3
    username: dbuser
    password: qtqnWTxzx6swe54rkcqY9YBNItv03103

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8094
  servlet:
    context-path: /iplstats


